import React, { useState } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import API_URL from '../config/api';
import Swal from 'sweetalert2';
import './AdminExport.css';

const AdminExport = () => {
    const [loading, setLoading] = useState(false);
    const userRole = localStorage.getItem('userRole');
    const headers = { 'x-user-role': userRole };

    const fetchFinancialData = async () => {
        const res = await axios.get(`${API_URL}/api/export/financial-report`, { headers });
        return res.data;
    };

    const exportFinancialReportPDF = async () => {
        setLoading(true);
        const shopName = localStorage.getItem('shopName') || 'E-Debt Store';
        const ownerName = localStorage.getItem('ownerName') || 'Admin';

        Swal.fire({
            title: 'Generating PDF Report...',
            text: 'Please wait while we compile your financial data.',
            allowOutsideClick: false,
            didOpen: () => Swal.showLoading()
        });

        try {
            const reportData = await fetchFinancialData();
            const doc = new jsPDF({ format: 'letter' });
            const dateStr = new Date().toLocaleDateString();

            // Header
            doc.setFontSize(20);
            doc.setTextColor(40, 40, 40);
            doc.text(`${shopName} - Financial Report`, 14, 22);

            doc.setFontSize(11);
            doc.setTextColor(100, 100, 100);
            doc.text(`Generated by: ${ownerName}`, 14, 30);
            doc.text(`Date: ${dateStr}`, 14, 36);

            // Table
            autoTable(doc, {
                startY: 45,
                head: [['Customer Name', 'Outstanding Balance', 'First Borrowed', 'Last Borrowed']],
                body: [
                    ...reportData.map(c => [
                        c.name,
                        `P ${(c.balance || 0).toFixed(2)}`,
                        c.first_borrow ? new Date(c.first_borrow).toLocaleDateString() : '—',
                        c.last_borrow ? new Date(c.last_borrow).toLocaleDateString() : '—'
                    ]),
                    [
                        { content: 'TOTAL', styles: { fontStyle: 'bold', fillColor: [240, 240, 240] } },
                        { content: `P ${reportData.reduce((s, c) => s + (c.balance || 0), 0).toFixed(2)}`, styles: { fontStyle: 'bold', fillColor: [240, 240, 240] } },
                        { content: '', styles: { fillColor: [240, 240, 240] } },
                        { content: '', styles: { fillColor: [240, 240, 240] } }
                    ]
                ],
                theme: 'striped',
                headStyles: { fillColor: [99, 102, 241] },
                styles: { fontSize: 10 },
                didDrawCell: () => { }
            });

            doc.save(`Financial_Report_${dateStr.replace(/\//g, '-')}.pdf`);
            Swal.fire({ icon: 'success', title: 'Export Complete', text: 'Your PDF report has been downloaded.' });

        } catch (err) {
            console.error("Export failed:", err);
            Swal.fire({ icon: 'error', title: 'Export Failed', text: 'Could not generate PDF.' });
        } finally {
            setLoading(false);
        }
    };

    const exportFinancialReportCSV = async () => {
        setLoading(true);
        try {
            const reportData = await fetchFinancialData();
            const csvRows = [
                ['Customer Name', 'Outstanding Balance', 'First Borrowed', 'Last Borrowed'],
                ...reportData.map(c => [
                    `"${c.name}"`,
                    `"P ${(c.balance || 0).toFixed(2)}"`,
                    c.first_borrow ? new Date(c.first_borrow).toLocaleDateString() : '—',
                    c.last_borrow ? new Date(c.last_borrow).toLocaleDateString() : '—'
                ]),
                ['TOTAL', `"P ${reportData.reduce((s, c) => s + (c.balance || 0), 0).toFixed(2)}"`, '', '']
            ];

            const csv = csvRows.map(r => r.join(',')).join('\n');
            const blob = new Blob([csv], { type: 'text/csv' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `Financial_Report_${new Date().toLocaleDateString().replace(/\//g, '-')}.csv`;
            a.click();
            URL.revokeObjectURL(url);

            Swal.fire({ icon: 'success', title: 'Exported!', text: 'Financial CSV downloaded', timer: 1500, showConfirmButton: false });
        } catch (err) {
            Swal.fire({ icon: 'error', title: 'Error', text: 'Failed to export CSV' });
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="admin-export">
            <p className="export-intro">Generate and download the store financial summary report.</p>

            {loading && (
                <div className="export-loading">
                    <div className="spinner"></div>
                    <span>Processing report...</span>
                </div>
            )}

            <div className="export-grid single-card">
                <div className="export-card">
                    <div className="export-card-icon">📊</div>
                    <h3>Financial Report</h3>
                    <p>Complete summary of debts, including first and last borrowing dates for all customers.</p>
                    <div className="export-actions">
                        <button className="btn-export pdf" onClick={exportFinancialReportPDF} disabled={loading}>📕 PDF Report</button>
                        <button className="btn-export csv" onClick={exportFinancialReportCSV} disabled={loading}>📗 CSV Report</button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default AdminExport;
