import React, { useState, useEffect } from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import axios from 'axios';
import Swal from 'sweetalert2';
import API_URL from '../config/api';
import './Settings.css';

const Settings = ({ onBack, onLogout, darkMode, toggleDarkMode }) => {
    const [shopName, setShopName] = useState(localStorage.getItem('shopName') || 'My Digital Store');
    const [ownerName, setOwnerName] = useState(localStorage.getItem('ownerName') || 'Admin');
    const [exporting, setExporting] = useState(false);

    // Toast Configuration
    const Toast = Swal.mixin({
        toast: true,
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000,
        timerProgressBar: true,
        didOpen: (toast) => {
            toast.addEventListener('mouseenter', Swal.stopTimer)
            toast.addEventListener('mouseleave', Swal.resumeTimer)
        }
    });

    // Save settings
    const handleSave = () => {
        localStorage.setItem('shopName', shopName);
        localStorage.setItem('ownerName', ownerName);
        Toast.fire({
            icon: 'success',
            title: 'Settings saved successfully!'
        });
    };

    const handleExportPDF = async () => {
        if (exporting) return;
        setExporting(true);

        // Show loading state
        Swal.fire({
            title: 'Generating PDF...',
            text: 'Please wait while we compile your report.',
            allowOutsideClick: false,
            didOpen: () => {
                Swal.showLoading();
            }
        });

        try {
            // Fetch latest customer data only
            const customersRes = await axios.get(`${API_URL}/api/customers`);

            const doc = new jsPDF({ format: 'letter' });
            const dateStr = new Date().toLocaleDateString();

            // Header
            doc.setFontSize(20);
            doc.setTextColor(40, 40, 40);
            doc.text(`${shopName} - Financial Report`, 14, 22);

            doc.setFontSize(11);
            doc.setTextColor(100, 100, 100);
            doc.text(`Generated by: ${ownerName}`, 14, 30);
            doc.text(`Date: ${dateStr}`, 14, 36);

            // 1. Customer Debts Section
            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text("Customer Debt List", 14, 50);

            // Filter only positive debts (optional, based on logic but keeping all for ledger)
            // Using "P" instead of symbol to avoid font encoding issues in standard jsPDF
            const debtData = customersRes.data
                .sort((a, b) => b.balance - a.balance)
                .map(c => [
                    c.name || 'Unknown',
                    c.unique_id,
                    `P ${c.balance.toFixed(2)}`
                ]);

            const totalDebt = customersRes.data.reduce((acc, c) => acc + (c.balance > 0 ? c.balance : 0), 0);

            autoTable(doc, {
                startY: 55,
                head: [['Customer Name', 'ID', 'Outstanding Balance']],
                body: [...debtData, ['', 'TOTAL DEBT', `P ${totalDebt.toFixed(2)}`]],
                theme: 'striped',
                headStyles: { fillColor: [220, 38, 38] },
                styles: { fontSize: 10 },
                footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' }
            });

            // Save
            doc.save(`Financial_Report_${dateStr.replace(/\//g, '-')}.pdf`);

            Swal.fire({
                icon: 'success',
                title: 'Export Complete',
                text: 'Your PDF report has been downloaded.',
                confirmButtonColor: '#4f46e5'
            });

        } catch (err) {
            console.error("Export failed:", err);
            Swal.fire({
                icon: 'error',
                title: 'Export Failed',
                text: 'Could not generate PDF. Please check connection.',
                confirmButtonColor: '#ef4444'
            });
        } finally {
            setExporting(false);
        }
    };

    const handleResetData = async () => {
        const result = await Swal.fire({
            title: '⚠️ Factory Reset',
            html: `
                <p>This will <b>PERMANENTLY DELETE</b> all order history and reset customer balances.</p>
                <p>Please enter the <b>Admin Password</b> to confirm:</p>
            `,
            input: 'password', // Change using password field
            inputAttributes: {
                autocapitalize: 'off',
                placeholder: 'Enter password',
                autocomplete: 'off',
                name: 'reset-password-field' // Random name to prevent manager matching
            },
            showCancelButton: true,
            confirmButtonText: 'Verify & Delete',
            confirmButtonColor: '#ef4444',
            showLoaderOnConfirm: true,
            preConfirm: async (input) => {
                // Hardcoded password verification
                if (input !== 'admin123') {
                    Swal.showValidationMessage('Incorrect password. Access denied.');
                } else {
                    try {
                        const response = await axios.post(`${API_URL}/api/reset`, { action: 'FULL_RESET' });
                        return response.data;
                    } catch (error) {
                        Swal.showValidationMessage(
                            `Request failed: ${error.response ? error.response.data.message : error.message}`
                        )
                    }
                }
            },
            allowOutsideClick: () => !Swal.isLoading()
        });

        if (result.isConfirmed) {
            Swal.fire({
                icon: 'success',
                title: 'System Reset!',
                text: 'All data has been cleared successfully.',
                confirmButtonColor: '#4f46e5'
            }).then(() => {
                window.location.reload();
            });
        }
    };

    return (
        <div className="settings-page fade-in">
            <div className="settings-header">
                <h2>Settings</h2>
            </div>

            <div className="settings-content">
                {/* Profile Section */}
                <div className="settings-card">
                    <h3>Store Profile</h3>
                    <div className="setting-item">
                        <label>Shop Name</label>
                        <input
                            type="text"
                            value={shopName}
                            onChange={(e) => setShopName(e.target.value)}
                            className="settings-input"
                        />
                    </div>
                    <div className="setting-item">
                        <label>Owner Name</label>
                        <input
                            type="text"
                            value={ownerName}
                            onChange={(e) => setOwnerName(e.target.value)}
                            className="settings-input"
                        />
                    </div>
                    <button className="button button-primary" onClick={handleSave}>
                        Save Changes
                    </button>
                </div>

                {/* Data Management Section */}
                <div className="settings-card">
                    <h3>Data Management</h3>
                    <div className="setting-row">
                        <div className="setting-info">
                            <h4>Export Data</h4>
                            <p>Download Customer Debt & Price List as PDF</p>
                        </div>
                        <button
                            className="button button-secondary export-btn"
                            onClick={handleExportPDF}
                            disabled={exporting}
                        >
                            {exporting ? 'Generating...' : '📄 Download PDF'}
                        </button>
                    </div>

                    <div className="setting-row danger-zone">
                        <div className="setting-info">
                            <h4 className="text-danger">Factory Reset</h4>
                            <p>Delete all orders and reset balances</p>
                        </div>
                        <button
                            className="button button-danger"
                            onClick={handleResetData}
                        >
                            ⚠️ Reset Data
                        </button>
                    </div>
                </div>

                {/* Appearance Section */}
                <div className="settings-card">
                    <h3>App Preferences</h3>
                    <div className="setting-row">
                        <div className="setting-info">
                            <h4>Dark Mode</h4>
                            <p>Switch between light and dark themes</p>
                        </div>
                        <div className="toggle-switch-container">
                            <div className={`toggle-switch ${darkMode ? 'on' : 'off'}`} onClick={toggleDarkMode}>
                                <div className="toggle-handle"></div>
                            </div>
                        </div>
                    </div>

                    {/* Install PWA Button */}
                    <div className="setting-row">
                        <div className="setting-info">
                            <h4>Install App</h4>
                            <p>Add to home screen for offline use</p>
                        </div>
                        <button
                            className="button button-primary"
                            onClick={() => {
                                if (window.showInstallPrompt) {
                                    const prompted = window.showInstallPrompt();
                                    if (!prompted) {
                                        Swal.fire({
                                            icon: 'warning',
                                            title: 'Installation Not Ready',
                                            text: 'The browser is not showing the install prompt yet. Ensure you are on HTTPS, using Chrome/Safari, and have interacted with the page.',
                                            footer: 'Try refreshing the page or using the "Add to Home Screen" browser menu.'
                                        });
                                    }
                                } else {
                                    Swal.fire({
                                        icon: 'info',
                                        title: 'Manual Install Required',
                                        text: 'Please use the "Add to Home Screen" option in your browser menu.'
                                    });
                                }
                            }}
                        >
                            📲 Install
                        </button>
                    </div>
                </div>

                {/* Account Section */}
                <div className="settings-card">
                    <h3>Account</h3>
                    <div className="setting-row">
                        <div className="setting-info">
                            <h4>Admin Session</h4>
                            <p>Sign out of the application</p>
                        </div>
                        <button
                            className="button button-secondary"
                            onClick={() => {
                                Swal.fire({
                                    title: 'Sign Out?',
                                    text: "You will be returned to the login screen.",
                                    icon: 'question',
                                    showCancelButton: true,
                                    confirmButtonColor: '#4f46e5',
                                    cancelButtonColor: '#d33',
                                    confirmButtonText: 'Yes, Sign Out'
                                }).then((result) => {
                                    if (result.isConfirmed) {
                                        onLogout && onLogout();
                                    }
                                })
                            }}
                        >
                            Log Out
                        </button>
                    </div>
                </div>

                {/* About Section */}
                <div className="settings-card">
                    <h3>About</h3>
                    <div className="setting-row">
                        <span className="app-version">Version 1.0.0</span>
                    </div>
                    <div className="setting-row">
                        <span className="app-credit">2026</span>
                    </div>
                </div>
            </div>

            {/* Padding for bottom nav */}
            <div style={{ height: '80px' }}></div>
        </div>
    );
};

export default Settings;
